// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ShutForksFromOutsideCommand.h"
#include "Commands/ShutForksFromTouchingCommand.h"
#include "Commands/RaiseForksCommand.h"
#include "Commands/DriveToAutoZoneCommand.h"

PickupBinAndMoveForawrdCommandGroup::PickupBinAndMoveForawrdCommandGroup() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void PickupBinAndMoveForawrdCommandGroup::Initialize() {
	AddSequential(new ShutForksFromTouchingCommand());
	AddSequential(new RasieForksCommand());
	AddSequential(new DriveToAutoZoneCommand());
}

// Called repeatedly when this Command is scheduled to run
void PickupBinAndMoveForawrdCommandGroup::Execute() {

}

	// Make this return true when this Command no longer needs to run execute()
bool PickupBinAndMoveForawrdCommandGroup::IsFinished() {

}

// Called once after isFinished returns true
void PickupBinAndMoveForawrdCommandGroup::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void PickupBinAndMoveForawrdCommandGroup::Interrupted() {
	End();
}
