// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Turn90DegreesCCW.h"

Turn90DegreesCCW::Turn90DegreesCCW() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void Turn90DegreesCCW::Initialize() {
	Robot::driveTrain->ResetEncoders();
}

// Called repeatedly when this Command is scheduled to run
void Turn90DegreesCCW::Execute() {
	Robot::driveTrain->rightMotor->Set(0.5);
	Robot::driveTrain->leftMotor->Set(-0.3);
}

// Make this return true when this Command no longer needs to run execute()
bool Turn90DegreesCCW::IsFinished() {
	return Robot::driveTrain->OnTarget(22.3725);
}

// Called once after isFinished returns true
void Turn90DegreesCCW::End() {
	Robot::driveTrain->rightMotor->Set(0);
	Robot::driveTrain->rightMotor->Set(0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Turn90DegreesCCW::Interrupted() {
	End();

}
